### ISSUE TITLE
Web "client" doesn't seem to do anything

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#18]
http://roothack.org/web/xxxxx/index

I see the page with the following options (and respective forms):
Add an SSH Public Key
Start a game
Show game progress and information
Show game score
Capture a flag
End a running game

After filling in any of the forms and submitting, I am sent to the new URL, but shown the same index page with no additional information. Currently running Chrome Version 51.0.2704.103 m

**Comment by geothird** [comment]
Looking into this, its possible I forgot to double check the updates that were made for the cli on the web client.

**Comment by geothird** [comment]
The response should be shown at the top of the page above "Wargames Web Client Actions"

**Comment by aksnowman** [comment]
It looks like you're correct and the results were displaying at the head of the page, just were short single lines in no way differentiated so it wasn't noticeable. Would some kind of border or something help make this a bit more visible?

**Comment by geothird** [comment]
Yes, that should help, the page could also be combined so that actions are in a drop down and the form switches depending on the option selected, that way maybe both output and form could appear without scrolling up or down.
