### ISSUE TITLE
CLI client failing after install

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#20]
> $ roothack
> Traceback (most recent call last):
>   File "/usr/local/bin/roothack", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
>     raise DistributionNotFound(req)
> pkg_resources.DistributionNotFound: Naked

**Comment by aksnowman** [comment]
Had to run these additional commands:
```
# pip install naked
# pip install shellescape
```
May want documentation updated to reflect this?

**Comment by geothird** [comment]
It should install them however I may need to specify them specifically in the setup.py.

**Comment by geothird** [comment]
Added these packages to the setup requirements should install them now with --upgrade or regular install.
