### ISSUE TITLE
UX - start & end?

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#22]
In the application, it lists the commands "game start" and "game end", just curious... aren't verbs usually paired as Start & Stop, or Begin & End? I can understand that it's actually spinning up (starting) an instance, and that "stop" may feel like it implies the same as "suspend", it just felt a little inconsistent/unnatural so figured I'd bring it up in the off chance anyone could come up with something a little more natural.

**Comment by geothird** [comment]
This has been renamed from `game end` to `game stop`
