### ISSUE TITLE
Client shows pip install URL --update instead of --upgrade

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#23]
The client webpage correctly shows --upgrade, but the client just crashed on me and showed the command to run with --update instead of --upgrade.

**Comment by aksnowman** [comment]
It also uses files.allthingsconnect.com instead of what the webpage shows as files.roothack.org

**Comment by aksnowman** [comment]
Displays as follows:

```
Roothack updates available:
  -> pip install https://files.allthingsconnect.com/roothack-0x312e322e326234.tar.gz --update

```

**Comment by geothird** [comment]
This should also be resolved with this version

```shell
$ pip install http://files.roothack.org/clients/roothack-1.2.2b4.tar.gz
```
