### ISSUE TITLE
Gateway SSH message using wrong case -a

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#25]
The message seen when trying to SSH from the gateway to target shows:
`To connect use ssh key forwarding "ssh -a $gateway".`
The `-a` should be capitalized `-A` as `-a` does the exact opposite.

**Comment by geothird** [comment]
Will change the wording as its confusing, but it was intended to allow you to bypass your public key as that is how you get level1 and use `level2@host` etc to login if you want otherwise you can just use `su level2` to switch up a level.

**Comment by aksnowman** [comment]
Oh, it wasn't a matter of wording. See the following entries from the SSH MAN page. The issue is that `-a` (lowercase) does the exact opposite of what you want it to do, and just needs made uppercase.

```
     -A      Enables forwarding of the authentication agent connection.  This can also be
             specified on a per-host basis in a configuration file.
     -a      Disables forwarding of the authentication agent connection.

```
