### ISSUE TITLE
Gateway to level 1 broken?

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#26]
After speaking with Ocyrus, it sounds like level 1 may be broken. I used `-A` as instructed to connect to the gateway, and was not able to reach the target. I also verified on my local machine (via `ssh-add -L` and/or `ssh-add -l`) that my roothack key was loaded into the agent. Let me know if you guys need any additional info, as I'm not sure what else to include...

**Comment by geothird** [comment]
Yeah this is weird and I think I got the order of help wrong,  the help file in the gateway home directory is correct it says just `ssh host` which when using key forwarding lets you in with the public key you used to login to the gateway.

After this however once you get level1 you can use the disable key forwarding to then login as those users.

**Comment by aksnowman** [comment]
Looks like this is something unique to my setup. My standard account on my end isn't passing through the key for authentication properly, but when I tried a different account, it worked.
