### ISSUE TITLE
Can I find my capture key after I've already started a game?

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#27]
Example: I start a game one day, poke around, get disconnected overnight and it suspends... if I start up again the next day, is there any way I can find my capture key without starting the game over?

**Comment by geothird** [comment]
It is currently saved in the cli tool `~/.roothack.cfg` and it is used there by default if you just present the flag.  It is meant to be like your private key.  We can talk this through some more if its too inconvenient.
