### ISSUE TITLE
Unable to redeem flag via CLI

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#29]
```
jrush@bas:~/notes/roothack.org$ roothack --cmd "capture flag 4Y2t1dROaC4avy1d0ZiA R-MBv-QiuQ0
ch-8M1Oww"
Capturing flag...
 Flag required (Example: --flag <flag> <key>)
jrush@bas:~/notes/roothack.org$ roothack --flag 4Y2t1dROaC4avy1d0ZiA R-MBv-QiuQ0ch-8M1Oww   
Option required: try --help
```

Even tried with both --cmd  and --flag on the same command line, wasn't able to redeem. Redemption through --shell worked fine, however.

NOTE: I removed the first 2 characters of flag and capture key because I'm not sure if/when they are invalidated.

**Comment by geothird** [comment]
```shell
$ roothack --cmd "capture flag" --flag <flag here>
```
Should now work in the latest.
