### ISSUE TITLE
Shell - Any way to copy/paste and/or use up key to set command line to previous commands?

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#31]
While the shell is much more intuitive to use for the most part, some of the UX is definitely lacking. I can't copy/paste (using Putty, I can't copy via selecting text, or paste via right-click) as I can in a standard Linux shell. Also, would it be possible to hit the up arrow to pre-fill the shell command line with previous commands so a person doesn't have to keep retyping everything from scratch? This would make redeeming flags much easier, at least.

**Comment by geothird** [comment]
Selection is done via a key like option on the mac probably alt on windows.  

I do like the up arrow idea, I'm going to implement that.

**Comment by geothird** [comment]
Up arrow now exists in version 1.2.2b5
