### ISSUE TITLE
Erinys banner

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#32]
Logging into Erinys, before the proper Erinys banner, showed the following banner as well:
```
       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/
```
I was unable to immediately reproduce this.

**Comment by geothird** [comment]
Was this after a stop start game?

**Comment by aksnowman** [comment]
I think it was...





On Tue, Jul 26, 2016 at 5:21 AM -0800, "Geo" <notifications@github.com> wrote:












Was this after a stop start game?
