### ISSUE TITLE
Restrict path from 6->7 and 7->8?

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#33]
The following file is currently set to permissions `644` which means I was able to skip from level 6 to level 8 (technically from any level to level 8) bypassing level 7. Should the level 7 message have the level 7 password included, and `chmod 600` the following file in `/home/level7/` ? This should force users to go 6->7->8 properly.

`-rw-r--r--  1 level7 level7   17 Jul 22 18:34 private`

**Comment by geothird** [comment]
This should be resolved in the latest erinys update, there wasn't proper permissions as described.
