### ISSUE TITLE
Game status stuck as 'Status: Booting' for days

### ISSUE THREAD

**Issue by aksnowman** [Roothack/Issues#36]
Issue #35 or #34 may have locked the system into a point where `game status` is only showing `Status: Booting` for me. I have tried `game start`, `game stop`, `game suspend`, `game resume`. This may only be affecting me, but I think it might have been some kind of race condition or something from stop/start/stop/start in quick succession.

**Comment by geothird** [comment]
In the error from the other bug it set up a record but no game i removed this you should be ok now.
